### ISSUE TITLE
www-plugins/freshplayerplugin: depend media-libs/mesa:=[egl] might need update

### ISSUE THREAD

**Issue by Universebenzene** [prototype99/didos#75]
From media-libs/mesa-21.3.2, the egl option for meson is enable by default and not controlled by `egl` USE flag any more. So I think the depend `media-libs/mesa:=[egl]` could be changed into `media-libs/mesa:=[egl(+)]`

**Comment by Universebenzene** [comment]
@prototype99 You forgot to update the Manifest 😂

**Comment by prototype99** [comment]
Nah I stopped updating the manifest as a test and I never got complaints so I'll do that now
