### ISSUE TITLE
www-plugins/freshplayerplugin: dependency x11-libs/libva has moved to media-libs/libva

### ISSUE THREAD

**Issue by Universebenzene** [prototype99/didos#77]
The dependency x11-libs/libva has been moved to media-libs/libva [in the main tree](https://github.com/gentoo/gentoo/blob/master/profiles/updates/4Q-2022). [Line 34](https://github.com/prototype99/didos/blob/fde98bc4adb46aa3d6660c35969e1e76e833291a/www-plugins/freshplayerplugin/freshplayerplugin-0.3.9-r4.ebuild#L34) of the ebuild may need changing.

**Comment by prototype99** [comment]
should be solved now
